/**
 *
 *  Curvelink.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace amr_01
{
namespace amr_ros2
{

class Curvelink
{
  public:
    struct Cols
    {
        static const std::string _id_curve_link;
        static const std::string _id_start;
        static const std::string _id_end;
        static const std::string _control_point_1_x;
        static const std::string _control_point_1_y;
        static const std::string _control_point_2_x;
        static const std::string _control_point_2_y;
        static const std::string _map_id;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Curvelink(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Curvelink(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Curvelink(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Curvelink() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id_curve_link  */
    ///Get the value of the column id_curve_link, returns the default value if the column is null
    const int32_t &getValueOfIdCurveLink() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdCurveLink() const noexcept;
    ///Set the value of the column id_curve_link
    void setIdCurveLink(const int32_t &pIdCurveLink) noexcept;

    /**  For column id_start  */
    ///Get the value of the column id_start, returns the default value if the column is null
    const int32_t &getValueOfIdStart() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdStart() const noexcept;
    ///Set the value of the column id_start
    void setIdStart(const int32_t &pIdStart) noexcept;

    /**  For column id_end  */
    ///Get the value of the column id_end, returns the default value if the column is null
    const int32_t &getValueOfIdEnd() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdEnd() const noexcept;
    ///Set the value of the column id_end
    void setIdEnd(const int32_t &pIdEnd) noexcept;

    /**  For column control_point_1_x  */
    ///Get the value of the column control_point_1_x, returns the default value if the column is null
    const float &getValueOfControlPoint1X() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<float> &getControlPoint1X() const noexcept;
    ///Set the value of the column control_point_1_x
    void setControlPoint1X(const float &pControlPoint1X) noexcept;

    /**  For column control_point_1_y  */
    ///Get the value of the column control_point_1_y, returns the default value if the column is null
    const float &getValueOfControlPoint1Y() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<float> &getControlPoint1Y() const noexcept;
    ///Set the value of the column control_point_1_y
    void setControlPoint1Y(const float &pControlPoint1Y) noexcept;

    /**  For column control_point_2_x  */
    ///Get the value of the column control_point_2_x, returns the default value if the column is null
    const float &getValueOfControlPoint2X() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<float> &getControlPoint2X() const noexcept;
    ///Set the value of the column control_point_2_x
    void setControlPoint2X(const float &pControlPoint2X) noexcept;

    /**  For column control_point_2_y  */
    ///Get the value of the column control_point_2_y, returns the default value if the column is null
    const float &getValueOfControlPoint2Y() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<float> &getControlPoint2Y() const noexcept;
    ///Set the value of the column control_point_2_y
    void setControlPoint2Y(const float &pControlPoint2Y) noexcept;

    /**  For column map_id  */
    ///Get the value of the column map_id, returns the default value if the column is null
    const int32_t &getValueOfMapId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMapId() const noexcept;
    ///Set the value of the column map_id
    void setMapId(const int32_t &pMapId) noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Curvelink>;
    friend drogon::orm::BaseBuilder<Curvelink, true, true>;
    friend drogon::orm::BaseBuilder<Curvelink, true, false>;
    friend drogon::orm::BaseBuilder<Curvelink, false, true>;
    friend drogon::orm::BaseBuilder<Curvelink, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Curvelink>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> idCurveLink_;
    std::shared_ptr<int32_t> idStart_;
    std::shared_ptr<int32_t> idEnd_;
    std::shared_ptr<float> controlPoint1X_;
    std::shared_ptr<float> controlPoint1Y_;
    std::shared_ptr<float> controlPoint2X_;
    std::shared_ptr<float> controlPoint2Y_;
    std::shared_ptr<int32_t> mapId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id_curve_link = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id_curve_link = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id_curve_link,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "id_start,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "id_end,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "control_point_1_x,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "control_point_1_y,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "control_point_2_x,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "control_point_2_y,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "map_id,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace amr_ros2
} // namespace amr_01
} // namespace drogon_model
